# This workflow is being written to test the ci process in self-hosted runner


name: ci test

on:
  workflow_dispatch:

jobs:
  ci-test-locally:

    runs-on: self-hosted

    steps:
    - name: Install dependencies in the local system
      run: pnpm install
    - name: Build the project using pnpm as the package manager
      run: pnpm build

